# Use interface docker0
interface=docker0
# Explicitly specify the address to listen on
listen-address=172.17.0.1
# Apparently the docker0 interface is not available when dnsmasq
# service starts so it fails. This option makes dynamically
# created interfaces work in the same way as the default.
bind-dynamic
# Set systemd-resolved DNS server
server=127.0.0.53 
