font_family     Fantasque Sans Mono
font_size       12.0

adjust_line_height  5

window_margin_width     2
window_border_width     1pt
window_padding_width    1

single_window_margin_width 0

tab_bar_style       powerline

background_opacity 0.85

# foreground #dddddd
# background #000000

active_border_color #0ff
inactive_border_color #444

active_tab_foreground #111
active_tab_background #87B966

inactive_tab_foreground #666
inactive_tab_background #2F3440


enabled_layouts tall:bias=50;full_size=1;mirrored=false

